### ISSUE TITLE
Max Elixer Possibility?

### ISSUE THREAD

**Issue by thighspls** [TheUnknownCod3r/BO4-Lucy-Menu#12]
I was wondering if theirs a way to just give yourself max elixirs straight to 999 permanently?

**Comment by TheUnknownCod3r** [comment]
No, you can only give yourself Plasma, or the Elixir in game, there’s no way to change it as it’s saved server side not the client side.

**Comment by TheUnknownCod3r** [comment]
to elaborate on this since I replied to you on my phone yesterday, theres no way to actually edit the amount of Elixirs you have as its stored server side, not client side. The only reason we can give Plasma is because the game awards plasma in game, not the lobby like the Elixirs. You can Spoof them in game through the Elixir menu and they don't count towards your uses, or use the Plasma loop and unlock that way with an autoclicker, which is what I did.
