### ISSUE TITLE
Unlock all 

### ISSUE THREAD

**Issue by Dufiw** [TheUnknownCod3r/BO4-Lucy-Menu#24]
Hey, so i found out the reason for it not unlock the camos, you have to run the unlock all twice and then it actually unlocks everything. One issue is for the M1927 it doesn't unlock the camos except for Dark Matter as shown in the image
![image](https://github.com/TheUnknownCod3r/BO4-Lucy-Menu/assets/121215919/e6131262-22e4-4bdd-853a-1b5308c2eca7)

**Comment by TheUnknownCod3r** [comment]
right, First off, The Unlock All seems to work fine for me, I completely reset my modded account stats to level 1, ranked up to 55, then used Unlock All. It won't completely unlock everything unless you have all the weapons etc unlocked as well. I could possibly fix this by using an array to store the stringname values for each weapon, then check against the array instead of level.zombie_weapons like it does.

**Comment by Dufiw** [comment]
Yeah, that might be the solution for this, but can't really guarantee it.

**Comment by TheUnknownCod3r** [comment]
This will be fixed in the Next update.

**Comment by TheUnknownCod3r** [comment]
Fix is Posted! Thanks for the Bug report.
